@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dtlivehero.brasa.common.block.brasafurnace;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;